<?php

/**
 * @file
 * Defines schema for password_confirm fields
 */

/**
 * Implements hook_field_schema().
 */
function password_confirm_field_schema($field) {
  switch ($field['type']) {
    case 'password_confirm':
      $columns = array(
        'pass1' => array(
          'type' => 'varchar',
          'length' => 255,
          'not null' => FALSE,
        ),
      );
      break;
  }
  return array(
    'columns' => $columns,
  );
}
