<?php
/**
 * @file
 * password_field.install
 * Defines a database column for encrypted passwords
 */

/**
 * Create the Password Field database table.
 *
 * Implements hook_field_schema
 */
function password_field_field_schema($field) {
  return array(
    'columns' => array(
      'password_field' => array(
        'type'     => 'text',
        'not null' => FALSE,
        'default'  => NULL,
      ),
    ),
  );
}
