<?php

/**
 * Implements hook_form_alter().
 *
 * Adds the action and redirect fields. Used by node type edit and node edit forms.
 */
function node_save_redirect_form_alter(&$form, &$form_state, $form_id) {

  if (isset($form['#node_type'])) {

    // ADdd the new radios buttons to the submission vertical tab.
    $form['submission']['node_save_redirect'] = array(
      '#type' => 'radios',
      '#title' => t('Redirect after content creation'),
      '#options' => array(0 => t('Default'),
        1 => t('Return to Edit page after saving.'),
        2 => t('Return to Content Overview after saving.'),
        4 => t('Re-direct to My Workbench after saving'),
        3 => t('Re-direct to another location')),
      '#description' => t('Choose where the user should be sent after creating new content.'),
      '#default_value' => variable_get('node_save_redirect_' . $form['#node_type']->type, 0)
    );

    // Add a textfield to the submission vertical tab.
    $form['submission']['node_save_redirect_location'] = array(
      '#type' => 'textfield',
      '#title' => 'Custom Redirect Location',
      '#default_value' => variable_get('node_save_redirect_location_' . $form['#node_type']->type, ''),
      '#states' => array(
        'visible' => array(
          ':input[name="node_save_redirect"]' => array('value' => '3'),
        ),
      )
    );
  }

  // Add a new submit function.
  if (strstr($form_id, '_node_form')) {
    $form['actions']['submit']['#submit'][] = 'node_save_redirect_submit';
  }
}

/**
 * A function that is called when a node is saved.
 *
 * @param array $form
 * @param array $form_state
 */
function node_save_redirect_submit($form, &$form_state) {

  // load settings
  $node_save_redirect_settings = variable_get('node_save_redirect_' . $form['type']['#value'], NULL);
  $custom_location = variable_get('node_save_redirect_location_' . $form['type']['#value'], '');

  if (!is_null($node_save_redirect_settings)) {

    // A destination in $_GET always overrides the function arguments. @see drupal_goto
    unset($_GET['destination']);

    if ($node_save_redirect_settings == '1') {
      $form_state['redirect'] = 'node/' . $form_state['nid'] . '/edit';
    }
    else if ($node_save_redirect_settings == '2' && user_access('access content overview')) {
      $form_state['redirect'] = 'admin/content';
    }
    else if ($node_save_redirect_settings == '4' && user_access('access workbench')) {
      $form_state['redirect'] = 'admin/workbench';
    }
    else if ($node_save_redirect_settings == '3') {
      $options = drupal_parse_url($custom_location);
      $form_state['redirect'] = array($options['path'], array(
        'query' => $options['query'],
        'fragment' => $options['fragment']
      ));
    }
  }
}