name = portfolioPage
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = portfolioPage-layout

; Regions
;regions[branding]       = Branding
;regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Scripts
scripts[] = js/portfolioPage.behaviors.js

; Stylesheets
stylesheets[all][] = css/portfolioPage.layout.css
