<?php

/**
 * @file
 * Module bootstrap file.
 */


/**
 * Implements hook_STORE_KEY_mforms_init().
 */
function mforms_example_fs_store_example_mforms_init() {
  // Load desired store implementation.
  $store = MformsFormStateStore::getInstance('fs_store_example');
  // Load steps object.
  $steps = MformsSteps::getInstance($store);
  // Load desired controls implementation.
  $controls = MformsSimpleControls::getInstance($store, $steps);
  // Init the mforms.
  mforms_init_module('mforms_example', 'fs_store_example', $store, $controls);
}

/**
 * Implements hook_STORE_KEY_mforms_init().
 */
function mforms_example_session_store_example_mforms_init() {
  $store = MformsSessionStore::getInstance('session_store_example');
  $steps = MformsSteps::getInstance($store);

  // If using mustistep controls you need to explicitly define form steps and
  // its attributes.
  $controls = MformsMultiStepControls::getInstance($store, $steps, array(
    '_mforms_example_step1' => array('value' => 'step 1', 'weight' => -103),
    '_mforms_example_step2' => array('value' => 'step 2', 'weight' => -102),
    '_mforms_example_step3' => array('value' => 'step 3', 'weight' => -101),
    '_mforms_example_step4' => array('value' => 'step 4', 'weight' => -100),
  ));
  // Ajaxify the form stepping process.
  $controls->ajaxify();

  // Init the mforms.
  mforms_init_module('mforms_example', 'session_store_example', $store, $controls);
}

/**
 * Implements hook_STORE_KEY_mforms_init().
 */
function mforms_example_more_forms_1_mforms_init() {
  $store = MformsFormStateStore::getInstance('more_forms_1');
  $steps = MformsSteps::getInstance($store);
  $controls = MformsPPControls::getInstance($store, $steps);
  $controls->ajaxify();
  mforms_init_module('mforms_example', 'more_forms_1', $store, $controls);
}

/**
 * Implements hook_STORE_KEY_mforms_init().
 */
function mforms_example_more_forms_2_mforms_init() {
  $store = MformsFormStateStore::getInstance('more_forms_2');
  $steps = MformsSteps::getInstance($store);
  $controls = MformsPPControls::getInstance($store, $steps);
  $controls->ajaxify();
  mforms_init_module('mforms_example', 'more_forms_2', $store, $controls);
}

/**
 * Implements hook_STORE_KEY_mforms_init().
 */
function mforms_example_ajax_forms_mforms_init() {
  $store = MformsFormStateStore::getInstance('ajax_forms');
  $steps = MformsSteps::getInstance($store);
  $controls = MformsSimpleControls::getInstance($store, $steps);
  $controls->ajaxify();
  mforms_init_module('mforms_example', 'ajax_forms', $store, $controls);
}

/**
 * Implements of hook_menu().
 *
 */
function mforms_example_menu() {
  $items['mforms'] = array(
    'title' => 'Mforms example',
    'page callback' => 'mforms_example_summary',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['mforms/summary'] = array(
    'title' => 'Mforms summary',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['mforms/example/fs'] = array(
    'title' => 'Form state storage',
    'page callback' => 'mforms_example_fs_store_page',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'mforms_example.pages.inc',
  );
  $items['mforms/example/session'] = array(
    'title' => 'Session storage',
    'page callback' => 'mforms_example_session_store_page',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'mforms_example.pages.inc',
  );
  $items['mforms/example/more_forms'] = array(
    'title' => 'More forms',
    'page callback' => 'mforms_example_more_forms_page',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'mforms_example.pages.inc',
    'weight' => 1,
  );
  $items['mforms/example/ajax'] = array(
    'title' => 'Ajax forms',
    'page callback' => 'mforms_example_ajax_forms_page',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'mforms_example.pages.inc',
    'weight' => 1,
  );

  return $items;
}

/**
 * Summary info page.
 *
 * @return string
 *   Summary page content.
 */
function mforms_example_summary() {
  return t('<p>To see multiforms in action navigate to the</p>
  <h2><a href="@url_fs">Form state storage implementation page</a></h2>
  <p>to see simple multistep form using $form_state for the storage. Or navigate to the</p>
  <h2><a href="@url_session">Session storage implementation page</a></h2>
  <p>where you can see more complex form that persists filled in data even if you leave the page and return back.</p>
  <h2><a href="@url_ajax_forms">Multi step form with use of ajax</a></h2>
  <p>where part of the form is loaded on conditional user action via ajax.</p>
  <h2><a href="@url_more_forms">Page with several forms</a></h2>
  <p>where each can be put to edit mode.</p>',
  array(
    '@url_fs' => url('mforms/example/fs'),
    '@url_session' => url('mforms/example/session'),
    '@url_ajax_forms' => url('mforms/example/ajax'),
    '@url_more_forms' => url('mforms/example/more_forms'),
  ));
}
