<?php

/**
 * @file
 * Provides a form element that confirms two textfields are the same.
 */

/**
 * Implements hook_menu().
 */
function textfield_confirm_test_menu() {
  $items = array();

  $items['test1'] = array(
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('textfield_confirm_test_form_1'),
  );

  $items['test2'] = array(
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('textfield_confirm_test_form_2'),
  );

  return $items;
}

/**
 * Basic test form.
 */
function textfield_confirm_test_form_1(array $form, array &$form_state) {

  $form['testfield'] = array(
    '#type' => 'textfield_confirm',
    '#title' => t('The wrapper title'),
    '#description' => t('The wrapper description.'),
    '#primary_title' => t('Field one'),
    '#primary_description' => t('This is the first field.'),
    '#secondary_title' => t('Field two'),
    '#secondary_description' => t('This is the second field. The value must match the first field.'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Submit callback for textfield_confirm_test_form_1().
 */
function textfield_confirm_test_form_1_submit(array &$form, array &$form_state) {
  drupal_set_message(t('The input value was: @value.', array('@value' => $form_state['values']['testfield'])));
}

/**
 * Emailfield test form.
 */
function textfield_confirm_test_form_2(array $form, array &$form_state) {
  $form = textfield_confirm_test_form_1($form, $form_state);
  $form['testfield']['#type'] = 'emailfield_confirm';
  $form['#submit'][] = 'textfield_confirm_test_form_1_submit';

  return $form;
}
