<?php

/**
 * @file
 * Provide some example default page redirects for Page Manager Redirect
 *
 * The examples are not intended for actual use, but just as examples for
 * curious users of PMR.
 */

/**
 * Implements hook_ctools_plugin_api().
 *
 * If you do this, CTools will pick up default pages/handlers in
 * page_manager_redirect_examples.pages_default.inc.
 */
function page_manager_redirect_examples_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory() to let the system know
 * we implement task_handler, content_type and context plugins.
 */
function page_manager_redirect_examples_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'ctools') {
    return 'pages/' . $plugin;
  }
}

/**
 * Implements hook_user_view().
 *
 * Sets the user profile title to 'Author of xxx' if the node ID is in the query
 * string. It would get there from our story_author redirect.
 */
function page_manager_redirect_examples_user_view($account, $view_mode) {
  if (isset($_GET['nid'])) {
    $node = node_load($_GET['nid']);
    $title = t('Author of @node', array('@node' => check_plain($node->title)));
    drupal_set_title($title);
  }
}
